#!/bin/bash

this_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

bspwm_fifo="/tmp/bspwm-fifo"
source ${this_dir}/../config

list_monitors() {
  bspc query --monitors --names
};

set_config() {
  bspc config top_padding $top_padding
}; set_config

subscribe_bspwm() {
  bspc subscribe | ${juice_dir}/desktop > ~/fifo
}; subscribe_bspwm &
