#!/bin/bash

this_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

bspwm_fifo="/tmp/bspwm-fifo"
bspwm_lemon_fifo="/tmp/bspwm-lemon.fifo"
source ${this_dir}/../config

list_monitors() {
  bspc query --monitors --names
};

set_config() {
  bspc config top_padding $top_padding
}; set_config

subscribe_bspwm() {
  bspc subscribe desktop_focus | while read mesg; do
    echo "DESKTOP" $(${juice_dir}/desktop <<< "$mesg") >> "/tmp/lemon-fifo"
  done
}; subscribe_bspwm &

