#!/usr/bin/env bash

color_file="$HOME/.cache/wal/colors.json"
if [ -a "$color_file" ]; then
  color_data=$(cat "$color_file")
  
  background=$(jq -r .special.background <<< "$color_data")
  foreground=$(jq -r .special.foreground <<< "$color_data")
fi
