#!/bin/bash


dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
juice_dir="${dir}/juice"

source ${dir}/config

export PATH=$PATH:${dir}/util

subscribe_bspwm() {
  bspc subscribe | ${juice_dir}/desktop > "$bspwm_fifo"
}

desktop_info() {
  tail -n1 "$bspwm_fifo" >> "$lemon_fifo"
}

build_info() {
  orientation=${1:?}  
  eval juice='$'$orientation

  output=""
  for drop in ${juice[@]}; do
    echo ${drop^^} $(${juice_dir}/${drop}) >> "$lemon_fifo"
    sleep 1
  done
}

subscribe_bspwm &

while :; do
  build_info left &
  desktop_info &
  build_info right &
  sleep 1
done &

tail -f "$lemon_fifo" | "${dir}/format" | lemonbar -o 0 -f "$l_font_main" -o -9 -f "$l_font_icon_main" -f "$l_font_icon_fallback" -u 2 -p

