#!/bin/bash

killall format
killall lemonbar

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
juice_dir="${dir}/juice"

source ${dir}/config
source ${dir}/modules/bspwm
source ${dir}/modules/wal

echo "foreground: $foreground"
echo "background: $background"

export PATH=$PATH:${dir}/util

build_info() {
  orientation=${1:?}  
  eval juice='$'$orientation

  output=""
  for drop in ${juice[@]}; do
    echo ${drop^^} $(${juice_dir}/${drop}) >> "$lemon_fifo"
    sleep 1
  done
}

while :; do
  build_info left &
  #desktop_info &
  build_info right &
  sleep 1
done &

sleep 1

idx=0
offset=0
for monitor in $(list_monitors); do
  width=$(get_monitor_width "$monitor")
  tail -f "$lemon_fifo" \
    | "${dir}/format" "$idx" \
    | lemonbar -o 0 -f "$l_font_main" -o -9 -f "$l_font_icon_main" -f "$l_font_icon_fallback" -u 2 -p -B "$background" -F "$foreground" -g "$width"+"$offset" &

  idx=$(echo "$idx" + 1 | bc)
  offset=$(echo "$offset" + "$width" | bc)
done

