#!/usr/bin/env bash

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

uchar() {
  env printf "\u$*"
}

unicode=$(cat "${dir}/icons.json" | jq -r '.["'"$1"'"]')

if [[ "$unicode" != "null" ]]; then
  icon_result="$(uchar $(echo $unicode))"
  env printf "$icon_result "
else
  echo "$1"
fi 
