#!/usr/bin/env dash
# neeasade
# print icon for different symbols in a few different fonts
# targetting: awesome, siji, ionic.
# usage: $0  <icon_type/code>

if ! $p_icon_enable; then
exit
fi

case $1 in
# awesome, siji, ionic.
alpha)    icon='f51a';;
beta)     icon='f135';;
prod)     icon='f54c';;
snow)     icon='f2dc';;
desktop)  icon='f108';;
battery)  icon='f240';;
cloud)    icon='f6c3';;
clock)    icon='f017';;
cpu)      icon='f5d2';;
date)     icon='f073';;
file)     icon='f15c';;
folder)   icon='f07c';;
lock)     icon='f023';;
logoff)   icon='f08b';;
mail)     icon='f0e0';;
memory)   icon='f037';;
music)    icon='f025';;
next)     icon='f050';;
pause)    icon='f04c';;
play)     icon='f04b';;
prev)     icon='f049';;
rotate)   icon='f01e';;
shutdown) icon='f011';;
sound)    icon='f028';;
up)       icon='f062';;
world)    icon='ff0a';;
window)   icon='f2d0';;
linux)    icon='f17c';;
github)   icon='f09b';;
*)        icon="$*";;
esac

iconfont=awesome

icon_result="$(uchar $(echo $icon))"

env printf "$icon_result "
