#!/bin/bash

set -e

emp='[ ]'
foc='[•]'

monitor=${1:?}
data=$(bspc query -m "$monitor" -T)

find_focused_idx() {
  focusedDesktopId=$(jq .focusedDesktopId <<< "$data")
  focused=$(jq '.desktops[] | select(.id == '"$focusedDesktopId"')' <<< "$data")
  jq -r .name <<< "$focused"
}

render() {
  idx=$(find_focused_idx)
  case "$idx" in
    0)
      echo "$foc $emp $emp $emp $emp $emp"
      ;;
    1)
      echo "$emp $foc $emp $emp $emp $emp"
      ;;
    2)
      echo "$emp $emp $foc $emp $emp $emp"
      ;;
    3)
      echo "$emp $emp $emp $foc $emp $emp"
      ;;
    4)
      echo "$emp $emp $emp $emp $foc $emp"
      ;;
    5)
      echo "$emp $emp $emp $emp $emp $foc"
      ;;
    *)
      echo "invalid"
      ;;
  esac
}

render
