#!/bin/bash

context=$(kubectl config current-context)

if [[ "$context" == "azq-prod" ]]; then
  icon book-dead
  echo "prod"
elif [[ "$context" == "azq-beta-1.16" ]]; then
  icon crow
  echo "beta"
elif [[ "$context" == "azq-alpha" ]]; then
  icon cat
  echo "alpha"
else
  echo "$context"
fi

