#!/bin/bash

context=$(kubectl config current-context)

if [[ "$context" == "azq-prod" ]]; then
  icon book-dead
elif [[ "$context" == "azq-beta" ]]; then
  icon crow
elif [[ "$context" == "azq-alpha" ]]; then
  icon cat
fi

echo "$context" | cut -d '-' -f 2
