#!/bin/bash


if `ponymix is-muted`; then
  icon volume-mute
  echo "MMM"
else
  volume=$(ponymix get-volume)
  if [ "$volume" -ge 50 ]; then
    icon volume-up
  else
    icon volume-down
  fi
  echo $(ponymix get-volume)\%
fi
